/* soapClient.cpp
   Generated by gSOAP 2.8.21 from test.h

Copyright(C) 2000-2014, Robert van Engelen, Genivia Inc. All Rights Reserved.
The generated code is released under one of the following licenses:
GPL or Genivia's license for commercial use.
This program is released under the GPL with the additional exemption that
compiling, linking, and/or using OpenSSL is allowed.
*/

#if defined(__BORLANDC__)
#pragma option push -w-8060
#pragma option push -w-8004
#endif
#include "soapH.h"

SOAP_SOURCE_STAMP("@(#) soapClient.cpp ver 2.8.21 2015-03-21 05:24:50 GMT")


SOAP_FMAC5 int SOAP_FMAC6 soap_call___tempuri__HelloWorld(struct soap *soap, const char *soap_endpoint, const char *soap_action, _tempuri__HelloWorld *tempuri__HelloWorld, _tempuri__HelloWorldResponse &tempuri__HelloWorldResponse)
{	struct __tempuri__HelloWorld soap_tmp___tempuri__HelloWorld;
	if (soap_endpoint == NULL)
		soap_endpoint = "http://localhost:51060/webservice/Service.asmx";
	if (soap_action == NULL)
		soap_action = "http://tempuri.org/HelloWorld";
	soap_begin(soap);
	soap->encodingStyle = NULL;
	soap_tmp___tempuri__HelloWorld.tempuri__HelloWorld = tempuri__HelloWorld;
	soap_serializeheader(soap);
	soap_serialize___tempuri__HelloWorld(soap, &soap_tmp___tempuri__HelloWorld);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___tempuri__HelloWorld(soap, &soap_tmp___tempuri__HelloWorld, "-tempuri:HelloWorld", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_url(soap, soap_endpoint, NULL), soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___tempuri__HelloWorld(soap, &soap_tmp___tempuri__HelloWorld, "-tempuri:HelloWorld", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!&tempuri__HelloWorldResponse)
		return soap_closesock(soap);
	tempuri__HelloWorldResponse.soap_default(soap);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	tempuri__HelloWorldResponse.soap_get(soap, "tempuri:HelloWorldResponse", NULL);
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_call___tempuri__HelloWorld_(struct soap *soap, const char *soap_endpoint, const char *soap_action, _tempuri__HelloWorld *tempuri__HelloWorld, _tempuri__HelloWorldResponse &tempuri__HelloWorldResponse)
{	struct __tempuri__HelloWorld_ soap_tmp___tempuri__HelloWorld_;
	if (soap_endpoint == NULL)
		soap_endpoint = "http://localhost:51060/webservice/Service.asmx";
	if (soap_action == NULL)
		soap_action = "http://tempuri.org/HelloWorld";
	soap_begin(soap);
	soap->encodingStyle = NULL;
	soap_tmp___tempuri__HelloWorld_.tempuri__HelloWorld = tempuri__HelloWorld;
	soap_serializeheader(soap);
	soap_serialize___tempuri__HelloWorld_(soap, &soap_tmp___tempuri__HelloWorld_);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___tempuri__HelloWorld_(soap, &soap_tmp___tempuri__HelloWorld_, "-tempuri:HelloWorld", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_url(soap, soap_endpoint, NULL), soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___tempuri__HelloWorld_(soap, &soap_tmp___tempuri__HelloWorld_, "-tempuri:HelloWorld", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!&tempuri__HelloWorldResponse)
		return soap_closesock(soap);
	tempuri__HelloWorldResponse.soap_default(soap);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	tempuri__HelloWorldResponse.soap_get(soap, "tempuri:HelloWorldResponse", NULL);
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

#if defined(__BORLANDC__)
#pragma option pop
#pragma option pop
#endif

/* End of soapClient.cpp */
