// Reminder: Modify typemap.dat to customize the header file generated by wsdl2h
/* test.h
   Generated by wsdl2h 2.8.21 from http://localhost:51060/webservice/Service.asmx?WSDL and typemap.dat
   2015-03-21 05:24:04 GMT

   DO NOT INCLUDE THIS FILE DIRECTLY INTO YOUR PROJECT BUILDS
   USE THE soapcpp2-GENERATED SOURCE CODE FILES FOR YOUR PROJECT BUILDS

   gSOAP XML Web services tools.
   Copyright (C) 2000-2014 Robert van Engelen, Genivia Inc. All Rights Reserved.
   Part of this software is released under one of the following licenses:
   GPL or Genivia's license for commercial use.
*/

/** @page page_notes Notes

@note HINTS:
 - Run soapcpp2 on test.h to generate the SOAP/XML processing logic.
   Use soapcpp2 -I to specify paths for #import
   To build with STL, 'stlvector.h' is imported from 'import' dir in package.
   Use soapcpp2 -j to generate improved proxy and server classes.
 - Use wsdl2h -c and -s to generate pure C code or C++ code without STL.
 - Use 'typemap.dat' to control namespace bindings and type mappings.
   It is strongly recommended to customize the names of the namespace prefixes
   generated by wsdl2h. To do so, modify the prefix bindings in the Namespaces
   section below and add the modified lines to 'typemap.dat' to rerun wsdl2h.
 - Use Doxygen (www.doxygen.org) on this file to generate documentation.
 - Use wsdl2h -R to generate REST operations.
 - Use wsdl2h -nname to use name as the base namespace prefix instead of 'ns'.
 - Use wsdl2h -Nname for service prefix and produce multiple service bindings
 - Use wsdl2h -d to enable DOM support for xsd:anyType.
 - Use wsdl2h -g to auto-generate readers and writers for root elements.
 - Use wsdl2h -b to auto-generate bi-directional operations (duplex ops).
 - Struct/class members serialized as XML attributes are annotated with a '@'.
 - Struct/class members that have a special role are annotated with a '$'.

@warning
   DO NOT INCLUDE THIS ANNOTATED FILE DIRECTLY IN YOUR PROJECT SOURCE CODE.
   USE THE FILES GENERATED BY soapcpp2 FOR YOUR PROJECT'S SOURCE CODE:
   THE soapStub.h FILE CONTAINS THIS CONTENT WITHOUT ANNOTATIONS.

@copyright LICENSE:
@verbatim
--------------------------------------------------------------------------------
gSOAP XML Web services tools
Copyright (C) 2000-2014, Robert van Engelen, Genivia Inc. All Rights Reserved.

This software is released under one of the following licenses:
GPL or Genivia's license for commercial use.
--------------------------------------------------------------------------------
GPL license.

This program is free software; you can redistribute it and/or modify it under
the terms of the GNU General Public License as published by the Free Software
Foundation; either version 2 of the License, or (at your option) any later
version.

This program is distributed in the hope that it will be useful, but WITHOUT ANY
WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A
PARTICULAR PURPOSE. See the GNU General Public License for more details.

You should have received a copy of the GNU General Public License along with
this program; if not, write to the Free Software Foundation, Inc., 59 Temple
Place, Suite 330, Boston, MA 02111-1307 USA

Author contact information:
engelen@genivia.com / engelen@acm.org

This program is released under the GPL with the additional exemption that
compiling, linking, and/or using OpenSSL is allowed.
--------------------------------------------------------------------------------
A commercial-use license is available from Genivia, Inc., contact@genivia.com
--------------------------------------------------------------------------------
@endverbatim

*/


//gsoapopt w

/******************************************************************************\
 *                                                                            *
 * Definitions                                                                *
 *   http://tempuri.org/                                                      *
 *                                                                            *
\******************************************************************************/


/******************************************************************************\
 *                                                                            *
 * Import                                                                     *
 *                                                                            *
\******************************************************************************/


// STL vector containers (use option -s to remove STL dependency)
#import "stlvector.h"

/******************************************************************************\
 *                                                                            *
 * Schema Namespaces                                                          *
 *                                                                            *
\******************************************************************************/


/* NOTE:

It is strongly recommended to customize the names of the namespace prefixes
generated by wsdl2h. To do so, modify the prefix bindings below and add the
modified lines to typemap.dat to rerun wsdl2h:

tempuri = "http://tempuri.org/"

*/

#define SOAP_NAMESPACE_OF_tempuri	"http://tempuri.org/"
//gsoap tempuri schema namespace:	http://tempuri.org/
//gsoap tempuri schema elementForm:	qualified
//gsoap tempuri schema attributeForm:	unqualified

/******************************************************************************\
 *                                                                            *
 * Built-in Schema Types and Top-Level Elements and Attributes                *
 *                                                                            *
\******************************************************************************/


/******************************************************************************\
 *                                                                            *
 * Forward Declarations                                                       *
 *                                                                            *
\******************************************************************************/


//  Forward declaration of class _tempuri__HelloWorld.
class _tempuri__HelloWorld;

//  Forward declaration of class _tempuri__HelloWorldResponse.
class _tempuri__HelloWorldResponse;


/******************************************************************************\
 *                                                                            *
 * Schema Types and Top-Level Elements and Attributes                         *
 *   http://tempuri.org/                                                      *
 *                                                                            *
\******************************************************************************/


/******************************************************************************\
 *                                                                            *
 * Schema Complex Types and Top-Level Elements                                *
 *   http://tempuri.org/                                                      *
 *                                                                            *
\******************************************************************************/

/// @brief Top-level root element "http://tempuri.org/":HelloWorld
/// @brief "http://tempuri.org/":HelloWorld is a complexType.
///
/// class _tempuri__HelloWorld operations:
/// - soap_new__tempuri__HelloWorld(soap*) allocate
/// - soap_new__tempuri__HelloWorld(soap*, int num) allocate array
/// - soap_new_req__tempuri__HelloWorld(soap*, ...) allocate, set required members
/// - soap_new_set__tempuri__HelloWorld(soap*, ...) allocate, set all public members
/// - int soap_read__tempuri__HelloWorld(soap*, _tempuri__HelloWorld*) deserialize from a stream
/// - int soap_write__tempuri__HelloWorld(soap, _tempuri__HelloWorld*) serialize to a stream
class _tempuri__HelloWorld
{ public:
/// A handle to the soap struct that manages this instance (automatically set).
    struct soap                         *soap                          ;
};

/// @brief Top-level root element "http://tempuri.org/":HelloWorldResponse
/// @brief "http://tempuri.org/":HelloWorldResponse is a complexType.
///
/// class _tempuri__HelloWorldResponse operations:
/// - soap_new__tempuri__HelloWorldResponse(soap*) allocate
/// - soap_new__tempuri__HelloWorldResponse(soap*, int num) allocate array
/// - soap_new_req__tempuri__HelloWorldResponse(soap*, ...) allocate, set required members
/// - soap_new_set__tempuri__HelloWorldResponse(soap*, ...) allocate, set all public members
/// - int soap_read__tempuri__HelloWorldResponse(soap*, _tempuri__HelloWorldResponse*) deserialize from a stream
/// - int soap_write__tempuri__HelloWorldResponse(soap, _tempuri__HelloWorldResponse*) serialize to a stream
class _tempuri__HelloWorldResponse
{ public:
/// Element "HelloWorldResult" of XSD type xs:string.
    std::string*                         HelloWorldResult               0;	///< Optional element.
/// A handle to the soap struct that manages this instance (automatically set).
    struct soap                         *soap                          ;
};


/******************************************************************************\
 *                                                                            *
 * Additional Top-Level Elements                                              *
 *   http://tempuri.org/                                                      *
 *                                                                            *
\******************************************************************************/


/******************************************************************************\
 *                                                                            *
 * Additional Top-Level Attributes                                            *
 *   http://tempuri.org/                                                      *
 *                                                                            *
\******************************************************************************/


/******************************************************************************\
 *                                                                            *
 * Services                                                                   *
 *                                                                            *
\******************************************************************************/

// This service supports SOAP 1.2 namespaces:
#import "soap12.h"

//gsoap tempuri service name:	ServiceSoap 
//gsoap tempuri service type:	ServiceSoap 
//gsoap tempuri service port:	http://localhost:51060/webservice/Service.asmx 
//gsoap tempuri service namespace:	http://tempuri.org/ 
//gsoap tempuri service transport:	http://schemas.xmlsoap.org/soap/http 

/** @mainpage Service Definitions

@section Service_bindings Service Bindings

  - @ref ServiceSoap

@section Service_more More Information

  - @ref page_notes "Notes"

  - @ref page_XMLDataBinding "XML Data Binding"

  - @ref SOAP_ENV__Header "SOAP Header Content" (when applicable)

  - @ref SOAP_ENV__Detail "SOAP Fault Detail Content" (when applicable)


*/

/**

@page ServiceSoap Binding "ServiceSoap"

@section ServiceSoap_operations Operations of Binding "ServiceSoap"

  - @ref __tempuri__HelloWorld

  - @ref __tempuri__HelloWorld_

@section ServiceSoap_ports Endpoints of Binding "ServiceSoap"

  - http://localhost:51060/webservice/Service.asmx

@note Multiple service bindings collected as one, use wsdl2h option -Nname to produce a separate service for each binding


*/

/******************************************************************************\
 *                                                                            *
 * Service Binding                                                            *
 *   ServiceSoap                                                              *
 *                                                                            *
\******************************************************************************/


/******************************************************************************\
 *                                                                            *
 * Service Operation                                                          *
 *   __tempuri__HelloWorld                                                    *
 *                                                                            *
\******************************************************************************/


/** Operation "__tempuri__HelloWorld" of service binding "ServiceSoap".

  - SOAP document/literal style messaging

  - Action: "http://tempuri.org/HelloWorld"

  - Addressing input action: "http://tempuri.org/HelloWorld"

  - Addressing output action: "http://tempuri.org/HelloWorldResponse"

C stub function (defined in soapClient.c[pp] generated by soapcpp2):
@code
  int soap_call___tempuri__HelloWorld(
    struct soap *soap,
    NULL, // char *endpoint = NULL selects default endpoint for this operation
    NULL, // char *action = NULL selects default action for this operation
    // input parameters:
    _tempuri__HelloWorld*               tempuri__HelloWorld,
    // output parameters:
    _tempuri__HelloWorldResponse       &tempuri__HelloWorldResponse
  );
@endcode

C server function (called from the service dispatcher defined in soapServer.c[pp]):
@code
  int __tempuri__HelloWorld(
    struct soap *soap,
    // input parameters:
    _tempuri__HelloWorld*               tempuri__HelloWorld,
    // output parameters:
    _tempuri__HelloWorldResponse       &tempuri__HelloWorldResponse
  );
@endcode

C++ proxy class (defined in soapServiceSoapProxy.h):
@code
  class ServiceSoapProxy;
@endcode
Important: use soapcpp2 option '-j' (or '-i') to generate improved and easy-to-use proxy classes;

C++ service class (defined in soapServiceSoapService.h):
@code
  class ServiceSoapService;
@endcode
Important: use soapcpp2 option '-j' (or '-i') to generate improved and easy-to-use service classes;

*/

//gsoap tempuri service method-protocol:	HelloWorld SOAP
//gsoap tempuri service method-style:	HelloWorld document
//gsoap tempuri service method-encoding:	HelloWorld literal
//gsoap tempuri service method-input-action:	HelloWorld http://tempuri.org/HelloWorld
//gsoap tempuri service method-output-action:	HelloWorld http://tempuri.org/HelloWorldResponse
int __tempuri__HelloWorld(
    _tempuri__HelloWorld*               tempuri__HelloWorld,	///< Input parameter
    _tempuri__HelloWorldResponse       &tempuri__HelloWorldResponse	///< Output parameter
);

/******************************************************************************\
 *                                                                            *
 * Service Operation                                                          *
 *   __tempuri__HelloWorld_                                                   *
 *                                                                            *
\******************************************************************************/


/** Operation "__tempuri__HelloWorld_" of service binding "ServiceSoap".

  - SOAP document/literal style messaging

  - Action: "http://tempuri.org/HelloWorld"

  - Addressing input action: "http://tempuri.org/HelloWorld"

  - Addressing output action: "http://tempuri.org/HelloWorldResponse"

C stub function (defined in soapClient.c[pp] generated by soapcpp2):
@code
  int soap_call___tempuri__HelloWorld_(
    struct soap *soap,
    NULL, // char *endpoint = NULL selects default endpoint for this operation
    NULL, // char *action = NULL selects default action for this operation
    // input parameters:
    _tempuri__HelloWorld*               tempuri__HelloWorld,
    // output parameters:
    _tempuri__HelloWorldResponse       &tempuri__HelloWorldResponse
  );
@endcode

C server function (called from the service dispatcher defined in soapServer.c[pp]):
@code
  int __tempuri__HelloWorld_(
    struct soap *soap,
    // input parameters:
    _tempuri__HelloWorld*               tempuri__HelloWorld,
    // output parameters:
    _tempuri__HelloWorldResponse       &tempuri__HelloWorldResponse
  );
@endcode

C++ proxy class (defined in soapServiceSoapProxy.h):
@code
  class ServiceSoapProxy;
@endcode
Important: use soapcpp2 option '-j' (or '-i') to generate improved and easy-to-use proxy classes;

C++ service class (defined in soapServiceSoapService.h):
@code
  class ServiceSoapService;
@endcode
Important: use soapcpp2 option '-j' (or '-i') to generate improved and easy-to-use service classes;

*/

//gsoap tempuri service method-protocol:	HelloWorld_ SOAP
//gsoap tempuri service method-style:	HelloWorld_ document
//gsoap tempuri service method-encoding:	HelloWorld_ literal
//gsoap tempuri service method-input-action:	HelloWorld_ http://tempuri.org/HelloWorld
//gsoap tempuri service method-output-action:	HelloWorld_ http://tempuri.org/HelloWorldResponse
int __tempuri__HelloWorld_(
    _tempuri__HelloWorld*               tempuri__HelloWorld,	///< Input parameter
    _tempuri__HelloWorldResponse       &tempuri__HelloWorldResponse	///< Output parameter
);

/**

@page ServiceSoap Binding "ServiceSoap"

@section ServiceSoap_policy_enablers Policy Enablers of Binding "ServiceSoap"

Based on policies, this service imports

  - WS-Policy reminders and enablers:
    - WS-Addressing 1.0 (2005/08, accepts 2004/08):
	@code
	#import "wsa5.h" // to be added to this header file for the soapcpp2 build step
	@endcode
	@code
	#include "plugin/wsaapi.h"
	soap_register_plugin(soap, soap_wsa); // register the wsa plugin in your code
	// See the user guide gsoap/doc/wsa/html/index.html
	@endcode
    - WS-Addressing (2004/08):
	@code
	#import "wsa.h" // to be added to this header file for the soapcpp2 build step
	@endcode
	@code
	#include "plugin/wsaapi.h"
	soap_register_plugin(soap, soap_wsa); // register the wsa plugin in your code
	// See the user guide gsoap/doc/wsa/html/index.html
	@endcode
    - WS-ReliableMessaging 1.0:
	@code
	#import "wsrm5.h" // to be added to this header file for the soapcpp2 build step
	@endcode
	@code
	#include "plugin/wsrmapi.h"
	soap_register_plugin(soap, soap_wsa); // register the wsa plugin in your code
	soap_register_plugin(soap, soap_wsrm); // register the wsrm plugin in your code
	// See the user guide gsoap/doc/wsrm/html/index.html
	@endcode
    - WS-ReliableMessaging 1.1:
	@code
	#import "wsrm.h" // to be added to this header file for the soapcpp2 build step
	@endcode
	@code
	#include "plugin/wsrmapi.h"
	soap_register_plugin(soap, soap_wsa); // register the wsa plugin in your code
	soap_register_plugin(soap, soap_wsrm); // register the wsrm plugin in your code
	// See the user guide gsoap/doc/wsrm/html/index.html
	@endcode
    - WS-Security (SOAP Message Security) 1.0 (accepts 1.1):
	@code
	#import "wsse.h" // to be added to this header file for the soapcpp2 build step
	@endcode
	@code
	#include "plugin/wsseapi.h"
	soap_register_plugin(soap, soap_wsse); // register the wsse plugin in your code
	// See the user guide gsoap/doc/wsse/html/index.html
	@endcode
    - WS-Security (SOAP Message Security) 1.1 (accepts 1.0):
	@code
	#import "wsse11.h" // to be added to this header file for the soapcpp2 build step
	@endcode
	@code
	#include "plugin/wsseapi.h"
	soap_register_plugin(soap, soap_wsse); // register the wsse plugin in your code
	// See the user guide gsoap/doc/wsse/html/index.html
	@endcode
    - HTTP Digest Authentication:
	@code
	#include "plugin/httpda.h"
	soap_register_plugin(soap, soap_http_da); // register the HTTP DA plugin in your code
	// See the user guide gsoap/doc/httpda/html/index.html
	@endcode
*/


/******************************************************************************\
 *                                                                            *
 * XML Data Binding                                                           *
 *                                                                            *
\******************************************************************************/


/**

@page page_XMLDataBinding XML Data Binding

SOAP/XML services use data bindings contractually bound by WSDL and auto-
generated by wsdl2h and soapcpp2 (see Service Bindings). Plain data bindings
are adopted from XML schemas as part of the WSDL types section or when running
wsdl2h on a set of schemas to produce non-SOAP-based XML data bindings.

The following readers and writers are C/C++ data type (de)serializers auto-
generated by wsdl2h and soapcpp2. Run soapcpp2 on this file to generate the
(de)serialization code, which is stored in soapC.c[pp]. Include "soapH.h" in
your code to import these data type and function declarations. Only use the
soapcpp2-generated files in your project build. Do not include the wsdl2h-
generated .h file in your code.

Data can be read in XML and deserialized from:
  - a file descriptor, using soap->recvfd = fd
  - a socket, using soap->socket = ...
  - a C++ stream, using soap->is = ...
  - a buffer, using the soap->frecv() callback

Data can be serialized in XML and written to:
  - a file descriptor, using soap->sendfd = fd
  - a socket, using soap->socket = ...
  - a C++ stream, using soap->os = ...
  - a buffer, using the soap->fsend() callback

The following options are available for (de)serialization control:
  - soap->encodingStyle = NULL; to remove SOAP 1.1/1.2 encodingStyle
  - soap_mode(soap, SOAP_XML_TREE); XML without id-ref (no cycles!)
  - soap_mode(soap, SOAP_XML_GRAPH); XML with id-ref (including cycles)
  - soap_set_namespaces(soap, struct Namespace *nsmap); to set xmlns bindings


@section tempuri Top-level root elements of schema "http://tempuri.org/"

  - <HelloWorld> @ref _tempuri__HelloWorld
    @code
    // Reader (returns SOAP_OK on success):
    soap_read__tempuri__HelloWorld(struct soap*, _tempuri__HelloWorld*);
    // Writer (returns SOAP_OK on success):
    soap_write__tempuri__HelloWorld(struct soap*, _tempuri__HelloWorld*);
    @endcode

  - <HelloWorldResponse> @ref _tempuri__HelloWorldResponse
    @code
    // Reader (returns SOAP_OK on success):
    soap_read__tempuri__HelloWorldResponse(struct soap*, _tempuri__HelloWorldResponse*);
    // Writer (returns SOAP_OK on success):
    soap_write__tempuri__HelloWorldResponse(struct soap*, _tempuri__HelloWorldResponse*);
    @endcode

*/

/* End of test.h */
